### ISSUE TITLE
Add functionality to get the history of a given feature

### ISSUE THREAD

**Issue by volaya** [koordinates/kart#496]
Just like now you can get a list of commits that affect a given layer, it should be possible to get the list of commits that affect a feature, given its id

**Comment by craigds** [comment]
at the moment this _can_ be done by finding out the internal path of the feature (somehow!) and doing:

`kart log HEAD -- datasetname/.table-dataset/feature/A/A/A/R/kc0EQA==`

... however that's not a real solution. But i would _like_ it to continue working, if possible, as it's a pretty handy feature for developers I think.

A better solution might be `kart log HEAD -- datasetname:<primarykey>`.

Since normal paths above shouldn't ever contain colons (related: #497) the parsing is unambiguous here.

**Comment by craigds** [comment]
This was fixed in #513 and will be in the 0.10.8 release.
