### ISSUE TITLE
Add option to diff command to get the meta changes in all layers

### ISSUE THREAD

**Issue by volaya** [koordinates/kart#514]
Now the meta changes for a given layer can be obtained using

`kart diff refa...refb datasetname:meta -ojson`

But there is no way of showing exisiting meta changes for all layers modified between the selected commits.

A bit of context for this: In the plugin, we are trying to detect whether there are meta changes or no before opening elements such as the diff viewer, which for now assume that the schema doesnt change

**Comment by craigds** [comment]
Obvious way to implement this would be:

```
kart diff refa...refb *:meta -ojson
```

Since we [forbid the * character](https://github.com/koordinates/kart/blob/master/docs/DATASETS_v3.md#valid-dataset-names) in dataset names, this results in unambiguous syntax.

The only obvious problem is that `*` will be expanded by shells to a filename, if a file matching that pattern exists in the current directory. That seems pretty unlikely though and it can always be quoted, so probably not a big deal.

- If we do this we should make it work for `*:feature` too
- Also `*:<featureID>` - this seems easy enough to make work, and means for a single-layer repo, the user doesn't have to use the actual dataset name, which they may not remember.
